[context.production.environment]
  REACT_APP_API_URL = "https://pandagarden-coronavirus-api.herokuapp.com/"
  REACT_APP_SENTRY_ENABLED = "true"

[context.dev.environment]
  REACT_APP_API_URL = "https://panda-coronavirus-api-staging.herokuapp.com/"
  REACT_APP_SENTRY_ENABLED = "false"

[[redirects]]
  from = "https://www.citamedicaencasa.com/*"
  to = "http://citamedicaencasa.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://citamedicaencasa.com/*"
  to = "http://citamedicaencasa.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/register/doctor"
  to = "/register/medicos-online"
  status = 301

[[redirects]]
  from = "/register/psychologist"
  to = "/register/psicologos-online"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
