export enum Routes {
    ABOUT_US = '/about-us',
    ADMIN_DASHBOARD = '/admin/dashboard',
    ADMIN_DASHBOARD_REGULAR = '/admin/dashboard/regular',
    ADMIN_DASHBOARD_PSYCHOLOGIST = '/admin/dashboard/psychologist',
    ADMIN_MODERATE = '/admin/moderate',
    ADMIN_STATS = '/admin/stats',
    DOCTOR_DASHBOARD = '/dashboard/doctor',
    DOCTOR_DASHBOARD_REGULAR = '/dashboard/doctor/regular',
    DOCTOR_DASHBOARD_PSYCHOLOGIST = '/dashboard/doctor/psychologist',
    GRATITUDES = '/gratitudes',
    HELP_CITIZEN = '/help/citizen',
    HELP_DOCTOR = '/help/doctor',
    DOCTOR_INQUIRIES = '/dashboard/doctor/inquiries',
    INQUIRY_DETAIL = '/dashboard/doctor/inquiry/:id',
    LOGIN = '/login',
    REGISTER = '/register',
    REGISTER_DOCTOR = '/register/medicos-online',
    REGISTER_PSYCHOLOGIST = '/register/psicologos-online',
    REGISTER_CITIZEN = '/register/citizen',
    ROOT = '/'
}
